<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nw_citavi"
 *
 * Auto generated by Extension Builder 2018-07-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Citavi Importer',
    'description' => '',
    'category' => 'misc',
    'author' => 'Lutz Eckelmann, Wolfgang Schröder',
    'author_email' => 'lutz.eckelmann@netzweber.de, wolfgang.schroeder@netzweber.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 'tx_nwcitavi',
    'createDirs' => 'fileadmin/user_upload/citavi_upload,fileadmin/user_upload/citavi_upload/export,fileadmin/user_upload/citavi_upload/files,fileadmin/user_upload/citavi_upload/log,fileadmin/user_upload/citavi_upload/backup,fileadmin/user_upload/citavi_upload/temp',
    'clearCacheOnLoad' => 0,
    'version' => '9.5.3',
    'constraints' => [
        'depends' => [
            'typo3' => '6.2.0-10.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
    'autoload' => [
      'psr-4' => [
        'Netzweber\\NwCitavi\\' => 'Classes'
      ]
    ],
];
